apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nginx:1.18-alpine
        name: nginx
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 256Mi
